version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
      - VITE_KAKAO_CLIENT_ID=b83227d4cddb2c0bc786056e2917f961
      - VITE_KAKAO_REDIRECT_URI=http://localhost:5173/kakao
    ports:
      - "5173:80"
    restart: always 
